package com.project3.prototype;

public class SalesReport implements Report
{
	private String title;
	private String header;
	private String footer;

	public SalesReport()
	{
		this.title="Monthly Sales Report";
		this.header="Company Confidential";
		this.footer="Generated By Reporting System";
		System.out.println("Loading Report Template From Disk");
	}

	@Override
	public Report clone()
	{
		try
		{
			return (Report) super.clone();
		}
		catch (CloneNotSupportedException e)
		{
			throw new RuntimeException(e);
		}
	}

	@Override
	public void generate(String data)
	{
		System.out.println(title);
		System.out.println(header);
		System.out.println(footer);
		System.out.println("______________________");
	}
}